const firebaseConfig = {
    apiKey: 'VOTRE_NEXT_PUBLIC_FIREBASE_API_KEY_ICI',
    authDomain: 'VOTRE_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_ICI',
    projectId: 'VOTRE_NEXT_PUBLIC_FIREBASE_PROJECT_ID_ICI',
    appId: 'VOTRE_NEXT_PUBLIC_FIREBASE_APP_ID_ICI'
};
